from __future__ import annotations

import pprint
import re
import base64
import mimetypes
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parent
VIEW_DIR = ROOT_DIR / "view"
HTML_DIR = VIEW_DIR / "html"
OUTPUT_FILE = ROOT_DIR / "frontend.py"

LINK_TAG_RE = re.compile(
    r'<link(?=[^>]*\brel=["\']stylesheet["\'])(?=[^>]*\bhref=["\'](?P<href>[^"\']+)["\'])[^>]*>',
    re.IGNORECASE,
)
SCRIPT_TAG_RE = re.compile(
    r'<script(?=[^>]*\bsrc=["\'](?P<src>[^"\']+)["\'])[^>]*>\s*</script>',
    re.IGNORECASE,
)
IMAGE_TAG_RE = re.compile(
    r'(<img\b[^>]*\bsrc=["\'])(?P<src>[^"\']+)(["\'][^>]*>)',
    re.IGNORECASE,
)


def to_posix(path: Path) -> str:
    return path.relative_to(ROOT_DIR).as_posix()


def resolve_relative_asset(html_path: Path, asset_ref: str) -> Path:
    return (html_path.parent / asset_ref).resolve()


def escape_inline_script(script_content: str) -> str:
    return script_content.replace("</script>", "<\\/script>")


def should_bundle_asset(asset_ref: str) -> bool:
    return not re.match(r"^(?:[a-z][a-z0-9+.-]*:|//|#)", asset_ref, re.IGNORECASE)


def encode_local_asset_as_data_url(asset_path: Path) -> str:
    mime_type, _ = mimetypes.guess_type(asset_path.name)
    if mime_type is None:
        mime_type = "application/octet-stream"
    encoded = base64.b64encode(asset_path.read_bytes()).decode("ascii")
    return f"data:{mime_type};base64,{encoded}"


def inline_linked_assets(html_path: Path, html_content: str) -> tuple[str, dict[str, str], dict[str, str]]:
    css_assets: dict[str, str] = {}
    js_assets: dict[str, str] = {}
    embedded_html = html_content

    def replace_link(match: re.Match[str]) -> str:
        href = match.group("href")
        css_path = resolve_relative_asset(html_path, href)
        css_content = css_path.read_text(encoding="utf-8")
        css_assets[to_posix(css_path)] = css_content
        return f'<style data-bundled-href="{href}">\n{css_content}\n</style>'

    def replace_script(match: re.Match[str]) -> str:
        src = match.group("src")
        script_path = resolve_relative_asset(html_path, src)
        script_content = script_path.read_text(encoding="utf-8")
        js_assets[to_posix(script_path)] = script_content
        safe_script = escape_inline_script(script_content)
        return f'<script data-bundled-src="{src}">\n{safe_script}\n</script>'

    def replace_image(match: re.Match[str]) -> str:
        src = match.group("src")
        if not should_bundle_asset(src):
            return match.group(0)
        image_path = resolve_relative_asset(html_path, src)
        data_url = encode_local_asset_as_data_url(image_path)
        return f'{match.group(1)}{data_url}{match.group(3)}'

    embedded_html = LINK_TAG_RE.sub(replace_link, embedded_html)
    embedded_html = SCRIPT_TAG_RE.sub(replace_script, embedded_html)
    embedded_html = IMAGE_TAG_RE.sub(replace_image, embedded_html)
    return embedded_html, css_assets, js_assets


def build_asset_record(html_path: Path) -> dict[str, object]:
    html_content = html_path.read_text(encoding="utf-8")
    embedded_html, css_assets, js_assets = inline_linked_assets(html_path, html_content)
    return {
        "name": to_posix(html_path),
        "html": html_content,
        "css": css_assets,
        "js": js_assets,
        "embedded_html": embedded_html,
    }


def build_asset_manifest() -> list[dict[str, object]]:
    if not HTML_DIR.exists():
        raise FileNotFoundError(f"HTML directory not found: {HTML_DIR}")

    assets: list[dict[str, object]] = []
    for html_path in sorted(HTML_DIR.rglob("*.html")):
        assets.append(build_asset_record(html_path))
    return assets


def render_frontend_module(assets: list[dict[str, object]]) -> str:
    asset_names = [asset["name"] for asset in assets]
    return "\n".join(
        [
            '"""Auto-generated by deploy_content.py. Do not edit manually."""',
            "",
            f"ASSETS = {pprint.pformat(assets, width=100, sort_dicts=False)}",
            "",
            "ASSET_INDEX = {asset['name']: asset for asset in ASSETS}",
            f"ASSET_NAMES = {pprint.pformat(asset_names, width=100)}",
            "",
        ]
    )


def generate_frontend_file() -> Path:
    assets = build_asset_manifest()
    OUTPUT_FILE.write_text(render_frontend_module(assets), encoding="utf-8")
    return OUTPUT_FILE


if __name__ == "__main__":
    output_path = generate_frontend_file()
    print(f"Generated {output_path}")
